# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - python-virtualenv/
    - target/

rust:test:
  stage: test
  script:
    - cargo install cargo2junit
    - cargo test --target-dir target/test --
      -Z unstable-options --format json --report-time |
      cargo2junit > report.xml # Generate test report
  artifacts:
    when: always
    reports:
      junit: report.xml

python:test:
  stage: test
  script:
    - python3 --version # For debugging
    - source simulate-with-python/setup-environment.sh # Also builds rust package
    - python simulate-with-python/main.py test_xml # Generate test report
  artifacts:
    when: always
    reports:
      junit: report.xml
